name: Release

on:
  pull_request:
  merge_group:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Check
        run: cargo check
      - name: Test
        run: cargo test --features=std
      - name: Dry run
        if: github.ref_type != 'tag'
        run: cargo publish --features=std --dry-run
      - uses: rust-lang/crates-io-auth-action@v1
        if: github.ref_type == 'tag'
        id: auth
      - name: Publish crate
        if: github.ref_type == 'tag'
        run: cargo publish --features=std
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
